### ISSUE TITLE
Using optional rust-postgres features without specifying them in Cargo.toml

### ISSUE THREAD

**Issue by mkovalchik** [s-panferov/deuterium#6]
Compilation of deuterium itself currently fails because the `rustc-serialize` and `time` features of rust-postgres are not specified in the Cargo.toml, but their `postgres::types::ToSql` implementation is depended upon.

Users of deuterium can work around the issue by specifying a dependency on rust-postgres and specifying the features themselves, but it would seem that either deuterium should either specify all of the features of the postgres dependency in its Cargo.toml or there should be equivalent `rustc-serialize` and `time` features in deuterium.

**Comment by s-panferov** [comment]
@mkovalchik thanks for report, will fix it tomorrow

**Comment by mkovalchik** [comment]
Since including all the optional features of rust-postgres as required didn't feel correct and it didn't seem right that cargo wouldn't support specifying transitive dependency features I had to take a look at it. 

Deuterium would have to specify features in its manifest that re-export the features to the postgres dependency: `uuid = ["postgres/uuid"]` (in addition to making all of the uuid bits optional in deuterium itself of course). Unfortunately until rust-lang/cargo#1286 gets closed it looks like it's not possible to have features be named the same as dependency names which would mean changing everything to have a prefix (`postgres-uuid = ["uuid", "postgres/uuid"]`?). Ostensibly deuterium supports mutltiple database dialects so that would get out of hand later but at least it works.

**Comment by s-panferov** [comment]
Hm, I don't see any features related to ` rustc-serialize` and `time` in rust-postgres. Only `uuid` is there. I think that problem is somewhere else.

**Comment by mkovalchik** [comment]
I don't believe there are explicit definitions in the manifest, it looks
like since there are optional dependencies named `time` and
`rustc-serialize` they can be used as implicit features. I only noticed
them because the readme in the repository talks about those two specifically

**Comment by palfrey** [comment]
I think this got solved when #15 got merged, if not before
